import { createContext } from "@lit/context";

export const videoContext =
  createContext<InteractiveVideoContext>("videoContext");

export class InteractiveVideoContext {
  // ******* TEACHER OPTIONS *******
  /**
   * Teacher options for showing overlays, initially set to true.
   */
  showOverlay: boolean = true;

  /**
   * Teacher options declaring whether the video has chapters, initially set to false.
   */
  hasChapters: boolean = true;

  /**
   * Teacher option to allow or disallow playback rate change, initially set to true.
   */
  allowPlaybackRateChange: boolean = true;

  // ******* VIDEO PROPERTIES *******

  /**
   * Video file as a base64 string for offline storage.
   */
  videoBase64: string = "";

  /**
   * Video URL for online playback.
   */
  videoURL: string = "";

  /**
   * Indicates whether the video is currently playing.
   * This property is reflected as an attribute.
   */
  videoLoaded: boolean = false;

  /**
   * Type of the video source.
   */
  videoType: string = "placeholder"; // "youtube", "vimeo", "spotify", "tiktok", "htmlvideo", "htmlaudio", "placeholder"

  /**
   * Details of the video such as title, author, and duration.
   */
  videoDetails: { title: string; author: string; duration: number } = {
    title: "",
    author: "",
    duration: 0,
  };

  /**
   * Waveform data for audio visualization generated by WaveSurfer.js.
   */
  waveformData: number[][] = null;

  // ******* CHAPTER PROPERTIES *******

  /**
   * Contains the current chapter configuration as an object.
   */
  chapterConfig: { title: string, startTime: number }[] = [];

  // ******* INTERACTION PROPERTIES *******

  /**
   * Indicates whether the interaction view is active.
   */
  selectedInteractionID: Number = -1;
}
